language: ruby
sudo: false
git:
  submodules: false

rvm:
  - 2.2.3

cache: bundler

services:
  - redis
  - redis-server

addons:
  postgresql: "9.4"

before_install:
  - bundle --version
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - rm .gitattributes
  - git submodule update --init --recursive

before_script:
  - psql -c 'create role quran_dev with login createdb;' -U postgres
  - bundle exec rake db:create
  - bundle exec rake db:load_pg_dump

script: "bundle exec rspec"
