language: ruby
sudo: false
git:
  submodules: false

rvm:
  - 2.2.3

cache: bundler

services:
  - redis
  - redis-server

addons:
  postgresql: "9.4"

before_install:
  - bundle --version
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - git submodule update --init --recursive
  - sudo curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  - sudo apt-get install git-lfs=1.0.2
  - git lfs init
  - ls -las db/dumps/2016-05-19_23:37:02

before_script:
  - psql -c 'create role quran_dev with login createdb;' -U postgres
  - bundle exec rake db:create
  - bundle exec rake db:load_pg_dump

script: "bundle exec rspec"
