language: ruby
git:
  submodules: false

rvm:
  - 3.1.0

cache: bundler

addons:
  postgresql: "9.4"
  apt:
    packages:
      - sshpass

before_install:
  - bundle --version
  - sshpass -p "$TRAVIS_PASSWORD" scp -o StrictHostKeyChecking=no travis@staging.quran.com:db/quran_dev.psql.bz2 db

before_script:
  - psql -c 'create role quran_dev with login createdb;' -U postgres
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:load_pg_dump

script: "bundle exec rspec"

notifications:
  email: false
