language: ruby
sudo: required
git:
  submodules: false

rvm:
  - 2.2.3

cache: bundler

services:
  - redis
  - redis-server

addons:
  postgresql: "9.4"

before_install:
  - bundle --version
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  - git submodule update --init --recursive
  - sudo apt-get install git-lfs
  - rm -rf db/dumps
  - ls db/dumps
  - cd db
  - rm -rf dumps/
  - ls dumps
  - git lfs install
  - git lfs pull
  - cd ..
  - ls db/dumps

before_script:
  - psql -c 'create role quran_dev with login createdb;' -U postgres
  - bundle exec rake db:create
  - bundle exec rake db:load_pg_dump

script: "bundle exec rspec"

notifications:
  email: false
