---
ayah:
    _source: { enabled: true }
    properties:
        ayah_index: { type: integer, index: not_analyzed }
        surah_id:   { type: integer, index: not_analyzed }
        ayah_num:   { type: integer, index: not_analyzed }
        page_num:   { type: integer, index: not_analyzed }
        juz_num:    { type: integer, index: not_analyzed }
        hizb_num:   { type: integer, index: not_analyzed }
        rub_num:    { type: integer, index: not_analyzed }
        sajdah:     { type: string,  index: not_analyzed }
        ayah_key:   { type: string,  index: not_analyzed }

# NOTE: field norms disabled because it seemed to mess up relevance scoring ( i.e. "norms: { enabled: true } " )
text:
    _parent: { type: ayah }
    _routing: { path: ayah_key }
    properties:
        text: { type: string, similarity: my_bm25, term_vector: with_positions_offsets_payloads, index: analyzed, search_analyzer: arabic_search, index_analyzer: arabic_index, norms: { enabled: true }   }
text_root:
    _parent: { type: ayah }
    _routing: { path: ayah_key }
    properties:
        text: { type: string, similarity: my_bm25, term_vector: with_positions_offsets_payloads, index: analyzed, search_analyzer: arabic_search, index_analyzer: arabic_index, norms: { enabled: true }   }

text_token:
    _parent: { type: ayah }
    _routing: { path: ayah_key }
    properties:
        text: { type: string, similarity: my_bm25, term_vector: with_positions_offsets_payloads, index: analyzed, search_analyzer: arabic_search, index_analyzer: arabic_index, norms: { enabled: true }  }
        clean: { type: string, term_vector: with_positions_offsets_payloads, index: analyzed, search_analyzer: arabic_search, index_analyzer: arabic_index, norms: { enabled: true }   }
#                    text:
#                        type: string
#                        term_vector: with_positions_offsets_payloads
#                        index: analyzed
#                        fields:
#                            ngram:
#                                type: string
#                                term_vector: with_positions_offsets_payloads
#                                index: analyzed
#                                index_analyzer:  arabic_ngram_index
#                                search_analyzer: arabic_ngram_query
#                            facet:
#                                type: string
#                                term_vector: with_positions_offsets_payloads
#                                index: analyzed
#                                index_analyzer:  arabic_facet_index
#                                search_analyzer: arabic_facet_query
text_stem:
    _parent: { type: ayah }
    _routing: { path: ayah_key }
    properties:
        text: { type: string, similarity: my_bm25, term_vector: with_positions_offsets_payloads, index: analyzed, search_analyzer: arabic_search, index_analyzer: arabic_index, norms: { enabled: true }   }
        clean: { type: string, term_vector: with_positions_offsets_payloads, index: analyzed, search_analyzer: arabic_search, index_analyzer: arabic_index, norms: { enabled: true }   }
text_lemma:
    _parent: { type: ayah }
    _routing: { path: ayah_key }
    properties:
        text: { type: string, similarity: my_bm25, term_vector: with_positions_offsets_payloads, index: analyzed, search_analyzer: arabic_search, index_analyzer: arabic_index, norms: { enabled: true }   }
        clean: { type: string, term_vector: with_positions_offsets_payloads, index: analyzed, search_analyzer: arabic_search, index_analyzer: arabic_index, norms: { enabled: true }   }
translation:
    _parent: { type: ayah }
    _routing: { path: ayah_key }
    properties:
        # NOTE experimenting with english stop words and stemmer
        text: { type: string, similarity: my_bm25, term_vector: with_positions_offsets_payloads, index: analyzed, search_analyzer: english, index_analyzer: english, norms: { enabled: true } }
transliteration:
    _parent: { type: ayah }
    _routing: { path: ayah_key }
    properties:
        text: { type: string, similarity: my_bm25, term_vector: with_positions_offsets_payloads, norms: { enabled: true } }
tafsir:
    _parent: { type: ayah }
    _routing: { path: ayah_key }
    properties:
        text: { type: string, similarity: my_bm25, term_vector: with_positions_offsets_payloads, index: analyzed, search_analyzer: arabic_search, index_analyzer: arabic_index, norms: { enabled: true }  }
