# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  database: quran_dev
  username: quran_dev
  password: dev_quran
  # username: quran
  # password: quran
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  schema_search_path: public,quran,"$user",content,audio,i18n

development:
  <<: *default

test:
  <<: *default
  database: quran_dev

production:
  <<: *default
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] %>
#  database: quran_production
#  username: quran
#  password: <%= ENV['QURAN_DATABASE_PASSWORD'] %>
#  dsn: dbi:Pg:dbname=quran
